version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net

  redis:
    image: redis:7
    networks:
      - app-net

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    environment:
      PGSSLMODE: disable
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${DATABASE_NAME}
      REDIS_URL: ${REDIS_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DB_HOST: postgres       # ← must match service name of Postgres
      DB_PORT: 5432
      DB_ADAPTER: ${DB_ADAPTER}
      DB_USER_NAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      DB_TEST_NAME: ${DB_TEST_NAME}
      DB_TEST_HOST: ${DB_TEST_HOST}
      DB_TEST_PORT: ${DB_TEST_PORT}
      DB_TEST_USER_NAME: ${DB_TEST_USER_NAME}
      DB_TEST_PASSWORD: ${DB_TEST_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - app-net

  sidekiq:
    build: .
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${DATABASE_NAME}
      REDIS_URL: ${REDIS_URL}
      PGSSLMODE: disable
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DB_HOST: postgres       # ← must match service name of Postgres
      DB_PORT: 5432
      DB_ADAPTER: ${DB_ADAPTER}
      DB_USER_NAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      DB_TEST_NAME: ${DB_TEST_NAME}
      DB_TEST_HOST: ${DB_TEST_HOST}
      DB_TEST_PORT: ${DB_TEST_PORT}
      DB_TEST_USER_NAME: ${DB_TEST_USER_NAME}
      DB_TEST_PASSWORD: ${DB_TEST_PASSWORD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    networks:
      - app-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - web
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
