version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7

  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    environment:
      RAILS_ENV: production
      DATABASE_URL: postgres://postgres:password@db:5432
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  pgdata:
